resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger:
  batch: true
  branches:
    include:
    - amd-staging
  paths:
    exclude:
    - .github
    - docs
    - '.*.y*ml'
    - '*.md'
    - LICENSE.txt

pr:
  autoCancel: true
  branches:
    include:
    - amd-staging
  paths:
    exclude:
    - .github
    - docs
    - '.*.y*ml'
    - '*.md'
    - LICENSE.txt
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/HIPIFY.yml@pipelines_repo
