/*
Copyright (c) 2015 - present Advanced Micro Devices, Inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

#include <sstream>
#include <regex>
#include "llvm/ADT/SmallString.h"
#include "CUDA2HIP.h"
#include "CUDA2HIP_Scripting.h"
#include "ArgParse.h"
#include "LLVMCompat.h"

namespace perl {

  using namespace std;
  using namespace llvm;
  using namespace hipify;

  const string sCopyright =
    "##\n"
    "# Copyright (c) 2015-present Advanced Micro Devices, Inc. All rights reserved.\n"
    "#\n"
    "# Permission is hereby granted, free of charge, to any person obtaining a copy\n"
    "# of this software and associated documentation files (the \"Software\"), to deal\n"
    "# in the Software without restriction, including without limitation the rights\n"
    "# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
    "# copies of the Software, and to permit persons to whom the Software is\n"
    "# furnished to do so, subject to the following conditions:\n"
    "#\n"
    "# The above copyright notice and this permission notice shall be included in\n"
    "# all copies or substantial portions of the Software.\n"
    "#\n"
    "# THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
    "# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
    "# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE\n"
    "# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
    "# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
    "# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
    "# THE SOFTWARE.\n"
    "##\n";

  const string sImportant = "# IMPORTANT: Do not change this file manually: it is generated by hipify-clang --perl";
  const string tab = "    ";
  const string tab_2 = tab + tab;
  const string tab_3 = tab_2 + tab;
  const string tab_4 = tab_3 + tab;
  const string tab_5 = tab_4 + tab;
  const string tab_6 = tab_5 + tab;
  const string tab_7 = tab_6 + tab;
  const string tab_8 = tab_7 + tab;
  const string tab_9 = tab_8 + tab;

  const string endl_2 = "\n\n";
  const string endl_tab = "\n" + tab;
  const string endl_tab_2 = "\n" + tab_2;
  const string endl_tab_3 = "\n" + tab_3;
  const string endl_tab_4 = "\n" + tab_4;
  const string endl_tab_5 = "\n" + tab_5;
  const string endl_tab_6 = "\n" + tab_6;

  const string sub = "sub ";
  const string my = "my ";
  const string my_k = my + "$k = 0;";
  const string while_ = "while ";
  const string unless_ = "unless ";
  const string foreach = "foreach ";
  const string foreach_func = foreach + "$func (";
  const string print = "print STDERR ";
  const string printf = "printf STDERR ";
  const string no_warns = "no warnings qw/uninitialized/;";
  const string hipify_perl = "hipify-perl";
  const string warning = "$fileName:$line_num: warning: ";
  const string sRocOnlyUnsupportedFunctions = "RocOnlyUnsupportedFunctions";
  const string sMIOpenOnlyUnsupportedFunctions = "MIOpenOnlyUnsupportedFunctions";
  const string sHipOnlyUnsupportedFunctions = "HipOnlyUnsupportedFunctions";
  const string sHipDNNOnlyUnsupportedFunctions = "HipDNNOnlyUnsupportedFunctions";
  const string sUnsupportedDeviceFunctions = "UnsupportedDeviceFunctions";
  const string sUnsupportedDeviceDataTypes = "UnsupportedDeviceDataTypes";
  const string sSimpleMappings = "simpleMappings";
  const string sSimpleIncludes = "simpleIncludes";
  const string sRocMappings = "rocMappings";
  const string sRocIncludes = "rocIncludes";
  const string sMIOpenMappings = "MIOpenMappings";
  const string sMIOpenIncludes = "MIOpenIncludes";
  const string sSubst = "subst";
  const string sExperimentalMappings = "experimentalMappings";
  const string sExperimentalIncludes = "experimentalIncludes";
  const string sTransformKernelLaunch = "transformKernelLaunch";
  const string sTransformCubNamespace = "transformCubNamespace";
  const string sSupportedDeviceFunctions = "SupportedDeviceFunctions";
  const string sSupportedDeviceDataTypes = "SupportedDeviceDataTypes";

  const string sCudaDevice = "cudaDevice";
  const string sCudaDeviceId = "cudaDeviceId";
  const string sCudaDevices = "cudaDevices";
  const string sCudaDevice_t = "cudaDevice_t";
  const string sCudaIDs = "cudaIDs";
  const string sCudaGridDim = "cudaGridDim";
  const string sCudaDimGrid = "cudaDimGrid";
  const string sCudaDimBlock = "cudaDimBlock";
  const string sCudaGradInput = "cudaGradInput";
  const string sCudaGradOutput = "cudaGradOutput";
  const string sCudaInput = "cudaInput";
  const string sCudaOutput = "cudaOutput";
  const string sCudaOprod = "cudaOprod";
  const string sCudaOprod_ex = "cudaOprod_ex";
  const string sCudaLongLinkOprod = "cudaLongLinkOprod";
  const string sCudaLongLinkOprod_ex = "cudaLongLinkOprod_ex";
  const string sCudaQuark = "cudaQuark";
  const string sCudaIndices = "cudaIndices";
  const string sCudaGaugeField = "cudaGaugeField";
  const string sCudaQdpGauge = "cudaQdpGauge";
  const string sCudaCpsGauge = "cudaCpsGauge";
  const string sCudaMom = "cudaMom";
  const string sCudaGauge = "cudaGauge";
  const string sCudaGauge_ex = "cudaGauge_ex";
  const string sCudaInGauge = "cudaInGauge";
  const string sCudaInGaugeEx = "cudaInGaugeEx";
  const string sCudaOutGauge = "cudaOutGauge";
  const string sCudaGaugeTemp = "cudaGaugeTemp";
  const string sCudaSpinorOut = "cudaSpinorOut";
  const string sCudaSpinor = "cudaSpinor";
  const string sCudaColorSpinorField = "cudaColorSpinorField";
  const string sCudaInLink = "cudaInLink";
  const string sCudaInLinkEx = "cudaInLinkEx";
  const string sCudaSiteLink = "cudaSiteLink";
  const string sCudaFatLink = "cudaFatLink";
  const string sCudaLongLink = "cudaLongLink";
  const string sCudaUnitarizedLink = "cudaUnitarizedLink";
  const string sCudaULink = "cudaULink";
  const string sCudaStaple = "cudaStaple";
  const string sCudaCloverField = "cudaCloverField";
  const string sCudaParam = "cudaParam";
  const string sCudaForce = "cudaForce";
  const string sCudaInForce = "cudaInForce";
  const string sCudaForce_ex = "cudaForce_ex";
  const string sCudaOutForce = "cudaOutForce";
  const string sCudaResult = "cudaResult";
  const string sCudaMemcpys ="cudaMemcpys";
  const string sCudaRitzVectors = "cudaRitzVectors";
  const string sCudaEigValueSet = "cudaEigValueSet";
  const string sCudaEigVecSet = "cudaEigVecSet";

  const set<string> Whitelist{
    {sCudaDevice}, {sCudaDevice_t}, {sCudaIDs}, {sCudaGridDim}, {sCudaDimGrid}, {sCudaDimBlock}, {sCudaDeviceId}, {sCudaDevices},
    {sCudaGradInput}, {sCudaGradOutput}, {sCudaInput}, {sCudaOutput}, {sCudaIndices}, {sCudaMom}, {sCudaGauge},
    {sCudaInGauge}, {sCudaSpinorOut}, {sCudaSpinor}, {sCudaColorSpinorField}, {sCudaSiteLink}, {sCudaFatLink}, {sCudaStaple}, {sCudaCloverField}, {sCudaParam}, {sCudaOutForce}, {sCudaGaugeTemp}, {sCudaResult}, {sCudaForce}, {sCudaInForce}, {sCudaForce_ex}, {sCudaOprod_ex}, {sCudaOutGauge}, {sCudaULink}, {sCudaOprod}, {sCudaGauge_ex}, {sCudaQuark}, {sCudaLongLinkOprod_ex}, {sCudaInGaugeEx}, {sCudaLongLink}, {sCudaUnitarizedLink}, {sCudaQdpGauge}, {sCudaCpsGauge}, {sCudaInLink}, {sCudaInLinkEx}, {sCudaGaugeField}, {sCudaMemcpys}, {sCudaRitzVectors}, {sCudaEigValueSet}, {sCudaLongLinkOprod}, {sCudaEigVecSet}
  };

  void generateHeader(ostream &out) {
    out << "#!/usr/bin/env perl" << endl_2;
    out << sCopyright << endl;
    out << sImportant << endl_2;
    out << "# USAGE" << endl;
    out << "#" << endl;
    out << "my $USAGE =<<USAGE;" << endl_2;
    out << "    hipify-perl is a tool to translate CUDA source code into portable HIP C++" << endl_2;
    out << "    USAGE: hipify-perl [OPTIONS] INPUT_FILE" << endl_2;
    out << "    OPTIONS:" << endl_2;
    out << "      -cuda-kernel-execution-syntax - Keep CUDA kernel launch syntax (default)" << endl;
    out << "      -examine                      - Combines -no-output and -print-stats options" << endl;
    out << "      -exclude-dirs=s               - Exclude directories" << endl;
    out << "      -exclude-files=s              - Exclude files" << endl;
    out << "      -experimental                 - HIPIFY experimentally supported APIs" << endl;
    out << "      -help                         - Display available options" << endl;
    out << "      -hip-kernel-execution-syntax  - Transform CUDA kernel launch syntax to a regular HIP function call (overrides \"--cuda-kernel-execution-syntax\")" << endl;
    out << "      -inplace                      - Backup the input file in .prehip file, modify the input file inplace" << endl;
    out << "      -miopen                       - Translate cuDNN to MIOpen instead of hipDNN where it is possible" << endl;
    out << "      -no-output                    - Don't write any translated output to stdout" << endl;
    out << "      -o=s                          - Output filename" << endl;
    out << "      -print-stats                  - Print translation statistics" << endl;
    out << "      -quiet-warnings               - Don't print warnings on unknown CUDA identifiers" << endl;
    out << "      -roc                          - Translate to roc instead of hip where it is possible" << endl;
    out << "      -version                      - The supported HIP version" << endl;
    out << "      -whitelist=s                  - Whitelist of identifiers" << endl;
    out << "USAGE" << endl;
    out << "#" << endl;
    out << "use warnings;" << endl;
    out << "use Cwd;" << endl;
    out << "use Getopt::Long;" << endl;
    out << "use File::Basename;" << endl;
    out << my << "$whitelist = \"\";" << endl;
    out << my << "$exclude_dirs =  \"\";" << endl;
    out << my << "$exclude_files = \"\";" << endl;
    out << my << "$fileName = \"\";" << endl;
    out << my << "$hipFileName = \"\";" << endl;
    out << my << "%ft;" << endl;
    out << my << "%tagsToConvertedTags = ();" << endl;
    out << my << "%tagsToConvertedTagsTotal = ();" << endl;
    out << my << "%convertedTags = ();" << endl;
    out << my << "%convertedTagsTotal = ();" << endl_2;
    out << "GetOptions(" << endl;
    out << tab << "  \"cuda-kernel-execution-syntax\" => \\$cuda_kernel_execution_syntax  # Keep CUDA kernel launch syntax (default)" << endl;
    out << tab << ", \"examine\" => \\$examine                                            # Combines -no-output and -print-stats options" << endl;
    out << tab << ", \"exclude-dirs=s\" => \\$exclude_dirs                                # Exclude directories" << endl;
    out << tab << ", \"exclude-files=s\" => \\$exclude_files                              # Exclude files" << endl;
    out << tab << ", \"experimental\" => \\$experimental                                  # HIPIFY experimentally supported APIs" << endl;
    out << tab << ", \"help\" => \\$help                                                  # Display available options" << endl;
    out << tab << ", \"hip-kernel-execution-syntax\" => \\$hip_kernel_execution_syntax    # Transform CUDA kernel launch syntax to a regular HIP function call (overrides \"--cuda-kernel-execution-syntax\")" << endl;
    out << tab << ", \"inplace\" => \\$inplace                                            # Backup the input file in .prehip file, modify the input file inplace" << endl;
    out << tab << ", \"no-output\" => \\$no_output                                        # Don't write any translated output to stdout" << endl;
    out << tab << ", \"miopen\" => \\$miopen                                              # Translate cuDNN to MIOpen instead of hipDNN where it is possible" << endl;
    out << tab << ", \"o=s\" => \\$hipFileName                                            # Output filename" << endl;
    out << tab << ", \"print-stats\" => \\$print_stats                                    # Print translation statistics" << endl;
    out << tab << ", \"quiet-warnings\" => \\$quiet_warnings                              # Don't print warnings on unknown CUDA identifiers" << endl;
    out << tab << ", \"roc\" => \\$roc                                                    # Translate to roc instead of hip where it is possible" << endl;
    out << tab << ", \"version\" => \\$version                                            # The supported HIP version" << endl;
    out << tab << ", \"whitelist=s\" => \\$whitelist                                      # Whitelist of identifiers" << endl;
    out << ");" << endl_2;
    out << "$cuda_kernel_execution_syntax = 1;" << endl_2;
    stringstream deprecated, removed, experimental, common;
    deprecated << my << "%deprecated_funcs = (" << endl;
    removed << my << "%removed_funcs = (" << endl;
    experimental << my << "%experimental_funcs = (" << endl;
    unsigned int countDeprecated = 0, countRemoved = 0, countExperimental = 0;
    for (auto ma = CUDA_RENAMES_MAP().rbegin(); ma != CUDA_RENAMES_MAP().rend(); ++ma) {
      bool bDeprecated = false, bRemoved = false, bExperimental = false;
      if (Statistics::isCudaDeprecated(ma->second)) bDeprecated = true;
      if (Statistics::isCudaRemoved(ma->second)) bRemoved = true;
      if (Statistics::isHipExperimental(ma->second)) bExperimental = true;
      if (bDeprecated || bRemoved) {
        const auto found = CUDA_VERSIONS_MAP().find(ma->first);
        if (found != CUDA_VERSIONS_MAP().end()) {
          if (bDeprecated) {
            deprecated << (countDeprecated ? ",\n" : "") << tab << "\"" << ma->first.str() << "\" => \"" << Statistics::getCudaVersion(found->second.deprecated) << "\"";
            countDeprecated++;
          }
          if (bRemoved) {
            removed << (countRemoved ? ",\n" : "") << tab << "\"" << ma->first.str() << "\" => \"" << Statistics::getCudaVersion(found->second.removed) << "\"";
            countRemoved++;
          }
        }
      }
      if (bExperimental) {
        const auto found = HIP_VERSIONS_MAP().find(ma->second.hipName);
        if (found != HIP_VERSIONS_MAP().end()) {
          experimental << (countExperimental ? ",\n" : "") << tab << "\"" << ma->first.str() << "\" => \"" << Statistics::getHipVersion(found->second.experimental) << "\"";
          countExperimental++;
        }
      }
    }
    common << endl << ");" << endl_2;
    deprecated << common.str();
    removed << common.str();
    experimental << common.str();
    out << deprecated.str();
    out << removed.str();
    out << experimental.str();
    out << "$print_stats = 1 if $examine;" << endl;
    out << "$no_output = 1 if $examine;" << endl_2;
    out << "# Whitelist of cuda[A-Z] identifiers, which are commonly used in CUDA sources but don't map to any CUDA API:" << endl;
    out << "@whitelist = (";
    unsigned int num = 0;
    for (const string &m : Whitelist) {
      out << endl_tab << (num ? ", " : "  ") << "\"" << m << "\"";
      ++num;
    }
    out << endl << ");" << endl_2;
    out << "push(@whitelist, split(',', $whitelist));" << endl;
    out << "push(@exclude_dirlist, split(',', $exclude_dirs));" << endl;
    out << "push(@exclude_filelist, split(',', $exclude_files));" << endl_2;
    out << "# Turn exclude dirlist and exclude_filelist into hash maps" << endl;
    out << "%exclude_dirhash = map { $_ => 1 } @exclude_dirlist;" << endl;
    out << "%exclude_filehash = map { $_ => 1 } @exclude_filelist;" << endl_2;
  }

  void generateStatFunctions(ostream &out) {
    out << endl << sub << "totalStats" << " {" << endl;
    out << tab << my << "%count = %{shift()};" << endl;
    out << tab << my << "$total = 0;" << endl;
    out << tab << foreach << "$key (keys %count) {" << endl;
    out << tab_2 << "$total += $count{$key};" << endl_tab << "}" << endl;
    out << tab << "return $total;" << endl << "}" << endl;
    out << endl << sub << "printStats" << " {" << endl;
    out << tab << my << "%counts    = %{shift()};" << endl;
    out << tab << my << "$warnings  = shift();" << endl;
    out << tab << my << "$loc       = shift();" << endl;
    out << tab << my << "$fileName  = shift();" << endl;
    out << tab << my << "$global    = shift();" << endl;
    out << tab << my << "$total     = totalStats(\\%counts);" << endl;
    out << tab << printf << "\"\\n[HIPIFY] info: file '$fileName' statistics:\\n\";" << endl;
    out << tab << printf << "\"  CONVERTED refs count: $total\\n\";" << endl;
    out << tab << printf << "\"  TOTAL lines of code: $loc\\n\";" << endl;
    out << tab << printf << "\"  WARNINGS: $warnings\\n\";" << endl;
    out << tab << printf << "\"[HIPIFY] info: CONVERTED refs by names:\\n\";" << endl;
    out << tab << "if ($global) {" << endl;
    out << tab_2 << foreach << my << "$key (sort keys %tagsToConvertedTagsTotal) {" << endl;
    out << tab_3 << printf << "\"  %s => %s: %d\\n\", $key, $tagsToConvertedTagsTotal{$key}, $convertedTagsTotal{$tagsToConvertedTagsTotal{$key}};" << endl;
    out << tab_2 << "}" << endl;
    out << tab << "} else {" << endl;
    out << tab_2 << foreach << my << "$key (sort keys %tagsToConvertedTags) {" << endl;
    out << tab_3 << printf << "\"  %s => %s: %d\\n\", $key, $tagsToConvertedTags{$key}, $convertedTags{$tagsToConvertedTags{$key}};" << endl;
    out << tab_2 << "}" << endl;
    out << tab << "}" << endl;
    out << "}" << endl;
    for (int i = 0; i < 2; ++i) {
      out << endl << sub << (i ? "clearStats" : "addStats") << " {" << endl;
      out << tab << my << "$dest_ref  = shift();" << endl;
      out << tab << my << (i ? "@statNames = @{shift()};" : "%adder     = %{shift()};") << endl;
      out << tab << foreach << "my " << (i ? "$stat(@statNames)" : "$key (keys %adder)") << " {" << endl;
      out << tab_2 << "$dest_ref->" << (i ? "{$stat} = 0;" : "{$key} += $adder{$key};") << endl_tab << "}" << endl << "}" << endl;
    }
  }

  void generateSubstFunction(ostream &out) {
    out << endl << sub << sSubst << " {" << endl;
    out << tab << my << "$a = shift();" << endl;
    out << tab << my << "$b = shift();" << endl;
    out << tab << my << "$t = shift();" << endl;
    out << tab << my << "$i = \"\";" << endl;
    out << tab << "if ($t eq \"include\" or $t eq \"include_cuda_main_header\")" << " {" << endl;
    out << tab_2 << "$i = \"(?<![\\\\!~`@#\\\\$%\\\\^&\\\\*\\\\-+=\\\\[\\\\]\\\\(\\\\)\\\\{\\\\}\\\\.\\\\,\\\\?'\\\\>])\";" << endl;
    out << tab << "}" << endl;
    out << tab << "if (my $c = s/$i\\b$a\\b/$b/g) {" << endl;
    out << tab_2 << "$ft{$t} += $c;" << endl;
    out << tab_2 << "$convertedTags{$b} +=$c;" << endl;
    out << tab_2 << "$convertedTagsTotal{$b} +=$c;" << endl;
    out << tab_2 << "$tagsToConvertedTags{$a} = $b;" << endl;
    out << tab_2 << "$tagsToConvertedTagsTotal{$a} = $b;" << endl;
    out << tab << "}" << endl;
    out << "}" << endl;
  }

  void generateExperimentalSubstitutions(ostream &out) {
    out << endl << sub << sExperimentalMappings << " {" << endl;
    for (auto &ma : CUDA_RENAMES_MAP()) {
      if (!Statistics::isHipExperimental(ma.second)) continue;
      if (ma.second.type != CONV_INCLUDE_CUDA_MAIN_H && ma.second.type != CONV_INCLUDE_CUDA_MAIN_V2_H && ma.second.type != CONV_INCLUDE) {
        out << tab << "k(\"" << ma.first.str() << "\", \"" << ma.second.hipName.str() << "\", \"" << counterNames[ma.second.type] << "\");" << endl;
      }
    }
    out << "}" << endl;
    out << endl << sub << sExperimentalIncludes << " {" << endl;
    for (auto &ma : CUDA_INCLUDE_MAP) {
      if (!Statistics::isHipExperimental(ma.second)) continue;
      if (ma.second.type == CONV_INCLUDE_CUDA_MAIN_H || ma.second.type == CONV_INCLUDE_CUDA_MAIN_V2_H || ma.second.type == CONV_INCLUDE) {
        string sCUDA = ma.first.str();
        string sHIP = ma.second.hipName.str();
        sCUDA = regex_replace(sCUDA, regex("/"), "\\/");
        sHIP = regex_replace(sHIP, regex("/"), "\\/");
        out << tab << "subst(\"" << sCUDA << "\", \"" << sHIP << "\", \"" << counterNames[ma.second.type] << "\");" << endl;
      }
    }
    out << "}" << endl;
  }

  void generateRocSubstitutions(ostream &out, bool bMIOpenOnly = false) {
    out << endl << sub << (bMIOpenOnly ? sMIOpenMappings : sRocMappings) << " {" << endl;
    bool bTranslateToRoc = TranslateToRoc;
    bool bTranslateToMIOpen = TranslateToMIOpen;
    if (bMIOpenOnly) TranslateToMIOpen = true;
    else TranslateToRoc = true;
    for (auto &ma : CUDA_RENAMES_MAP()) {
      if ((bMIOpenOnly && !Statistics::isToMIOpen(ma.second)) || Statistics::isUnsupported(ma.second) || ma.second.rocName.empty()) continue;
      if ((!bMIOpenOnly && Statistics::isToRoc(ma.second) && ma.second.apiType == API_DNN) || Statistics::isUnsupported(ma.second) || ma.second.rocName.empty()) continue;
      if (ma.second.type != CONV_INCLUDE_CUDA_MAIN_H && ma.second.type != CONV_INCLUDE_CUDA_MAIN_V2_H && ma.second.type != CONV_INCLUDE) {
        out << tab << "k(\"" << ma.first.str() << "\", \"" << ma.second.rocName.str() << "\", \"" << counterNames[ma.second.type] << "\");" << endl;
      }
    }
    out << "}" << endl;
    out << endl << sub << (bMIOpenOnly ? sMIOpenIncludes : sRocIncludes) << " {" << endl;
    for (auto &ma : CUDA_INCLUDE_MAP) {
      if (ma.second.type == CONV_INCLUDE_CUDA_MAIN_H || ma.second.type == CONV_INCLUDE_CUDA_MAIN_V2_H || ma.second.type == CONV_INCLUDE) {
        if (bMIOpenOnly) {
          if (!Statistics::isToMIOpen(ma.second)) continue;
        } else {
          if (!Statistics::isToRoc(ma.second)) continue;
        }
        string sROC = ma.second.rocName.str();
        if (sROC.empty()) continue;
        string sCUDA = ma.first.str();
        sCUDA = regex_replace(sCUDA, regex("/"), "\\/");
        sROC = regex_replace(sROC, regex("/"), "\\/");
        out << tab << "subst(\"" << sCUDA << "\", \"" << sROC << "\", \"" << counterNames[ma.second.type] << "\");" << endl;
      }
    }
    TranslateToRoc = bTranslateToRoc;
    TranslateToMIOpen = bTranslateToMIOpen;
    out << "}" << endl;
  }

  void generateSimpleSubstitutions(ostream &out) {
    out << endl << "sub k { $mappings{$_[0]} = { rep => $_[1], type => $_[2] }; }" << endl;
    out << endl << sub << sSimpleMappings << " {" << endl;
    for (auto &ma : CUDA_RENAMES_MAP()) {
      if (Statistics::isUnsupported(ma.second) || Statistics::isHipExperimental(ma.second)) continue;
      if (ma.second.type != CONV_INCLUDE_CUDA_MAIN_H && ma.second.type != CONV_INCLUDE_CUDA_MAIN_V2_H && ma.second.type != CONV_INCLUDE) {
        out << tab << "k(\"" << ma.first.str() << "\", \"" << ma.second.hipName.str() << "\", \"" << counterNames[ma.second.type] << "\");" << endl;
      }
    }
    out << "}" << endl;
    out << endl << sub << sSimpleIncludes << " {" << endl;
    for (auto &ma : CUDA_INCLUDE_MAP) {
      if (Statistics::isUnsupported(ma.second) || Statistics::isHipExperimental(ma.second)) continue;
      if (ma.second.type == CONV_INCLUDE_CUDA_MAIN_H || ma.second.type == CONV_INCLUDE_CUDA_MAIN_V2_H || ma.second.type == CONV_INCLUDE) {
        string sCUDA = ma.first.str();
        string sHIP = ma.second.hipName.str();
        sCUDA = regex_replace(sCUDA, regex("/"), "\\/");
        sHIP = regex_replace(sHIP, regex("/"), "\\/");
        out << tab << "subst(\"" << sCUDA << "\", \"" << sHIP << "\", \"" << counterNames[ma.second.type] << "\");" << endl;
      }
    }
    out << "}" << endl;
  }

  void generateKernelLaunch(ostream &out) {
    out << endl << "# CUDA Kernel Launch Syntax" << endl << sub << sTransformKernelLaunch << " {" << endl;
    out << tab << no_warns << endl << tab << my_k << endl_2;
    out << tab << "$k += s{([a-zA-Z_0-9:]+(?:\\s*<[^>]+>)?)\\s*<<<\\s*(.+?)\\s*>>>\\s*(\\(\\s*\\)|\\()}{do {" << endl;
    out << tab_2 << "my ($f, $c, $p) = ($1, $2, $3);" << endl;
    out << tab_2 << "my (@a, $d, $cur);" << endl;
    out << tab_2 << "foreach my $s (split //, $c) {" << endl;
    out << tab_3 << "if ($s =~ /[\\(\\[\\<]/) { $d++ } elsif ($s =~ /[\\)\\]\\>]/) { $d-- }" << endl;
    out << tab_3 << "if ($s eq ',' && $d == 0) { push @a, $cur; $cur = '' } else { $cur .= $s }" << endl;
    out << tab_2 << "} push @a, $cur;" << endl;
    out << tab_2 << "for my $i (0 .. $#a) { my $v = $a[$i]; $v =~ s/^\\s+|\\s+$//g; $v = '0' if $v eq ''; $a[$i] = $v; }" << endl;
    out << tab_2 << "push @a, ('0', '0', '0');" << endl;
    out << tab_2 << "for my $i (0..1) { $a[$i] = \"dim3($a[$i])\" unless $a[$i] =~ /^dim3\\b/; }" << endl;
    out << tab_2 << "$f = \"HIP_KERNEL_NAME($f)\" if $f =~ /</;" << endl;
    out << tab_2 << "my $res = \"hipLaunchKernelGGL($f, $a[0], $a[1], $a[2], $a[3]\" . ($p =~ /\\)/ ? \")\" : \", \");" << endl;
    out << tab_2 << "$res;" << endl;
    out << tab << "}}gexs;" << endl_2;
    out << tab << "if ($k) { $ft{'" << counterNames[CONV_KERNEL_LAUNCH] << "'} += $k; }" << endl;
    out << "}" << endl;
  }

  void generateCubNamespace(ostream &out) {
    out << endl << sub << sTransformCubNamespace << " {" << endl;
    out << tab << "s/using\\s*namespace\\s*cub/using namespace hipcub/g;" << endl;
    out << tab << "s/\\bcub::\\b/hipcub::/g;" << endl << "}" << endl;
  }

  void generateHostFunctions(ostream &out) {
    out << endl << sub << "transformHostFunctions" << " {" << endl;
    out << tab << "my $process_args = sub {" << endl;
    out << tab_2 << "my ($f, $args_str, $argIdx, $actionType, $cast) = @_;" << endl;
    out << tab_2 << "my $args_inner = substr($args_str, 1, -1);" << endl;
    out << tab_2 << "my (@a, $d, $cur);" << endl;
    out << tab_2 << "foreach my $s (split //, $args_inner) {" << endl;
    out << tab_3 << "if ($s =~ /[\\(\\[\\<\\{]/) { $d++ } elsif ($s =~ /[\\)\\]\\>\\}]/) { $d-- }" << endl;
    out << tab_3 << "if ($s eq ',' && $d == 0) { push @a, $cur; $cur = '' } else { $cur .= $s }" << endl;
    out << tab_2 << "} push @a, $cur;" << endl;
    out << tab_2 << "if (defined $a[$argIdx]) {" << endl;
    out << tab_3 << "my $v = $a[$argIdx]; $v =~ s/^\\s+|\\s+$//g;" << endl;
    out << tab_3 << "if ($actionType == 0 || $actionType == 1) {" << endl;
    out << tab_4 << "$a[$argIdx] = \"$cast($v)\" unless index($v, $cast) == 0;" << endl;
    out << tab_3 << "} elsif ($actionType == 2) {" << endl;
    out << tab_4 << "splice(@a, $argIdx, 1);" << endl;
    out << tab_3 << "}" << endl;
    out << tab_2 << "}" << endl;
    out << tab_2 << "return \"$f(\" . join(',', @a) . \")\";" << endl;
    out << tab << "};" << endl_2;
    set<string> DeviceSymbolFunctions0, DeviceSymbolFunctions1, DeviceSymbolFunctions2;
    set<string> DeviceSymbolFunctions3, DeviceSymbolFunctions4, DeviceSymbolFunctions5;
    set<string> ReinterpretFunctions0, ReinterpretFunctions1, RemoveArgFunctions3;
    for (auto f : FuncArgCasts) {
      auto castStructs = f.second;
      for (auto cc : castStructs) {
        for (auto c : cc.castMap) {
          switch (c.first) {
            case 0:
              switch (c.second.castType) {
                case e_HIP_SYMBOL: DeviceSymbolFunctions0.insert(f.first); break;
                case e_reinterpret_cast: ReinterpretFunctions0.insert(f.first); break;
                default: break;
              } break;
            case 1:
              switch (c.second.castType) {
                case e_HIP_SYMBOL: DeviceSymbolFunctions1.insert(f.first); break;
                case e_reinterpret_cast: ReinterpretFunctions1.insert(f.first); break;
                default: break;
              } break;
            case 2:
              if (c.second.castType == e_HIP_SYMBOL) DeviceSymbolFunctions2.insert(f.first); break;
            case 3:
              switch (c.second.castType) {
                case e_HIP_SYMBOL: DeviceSymbolFunctions3.insert(f.first); break;
                case e_remove_argument: RemoveArgFunctions3.insert(f.first); break;
                default: break;
              } break;
            case 4:
              if (c.second.castType == e_HIP_SYMBOL) DeviceSymbolFunctions4.insert(f.first); break;
            case 5:
              if (c.second.castType == e_HIP_SYMBOL) DeviceSymbolFunctions5.insert(f.first); break;
            default: break;
          }
        }
      }
    }
    set<string> *funcSet = &DeviceSymbolFunctions0;
    for (int i = 0; i < 9; ++i) {
      int argIdx = 0;
      int actionType = 0;
      string castStr = "";
      switch (i) {
        default:
        case 0:  funcSet = &DeviceSymbolFunctions0; argIdx = 0; actionType = 0; castStr = getCastType(e_HIP_SYMBOL); break;
        case 1:  funcSet = &DeviceSymbolFunctions1; argIdx = 1; actionType = 0; castStr = getCastType(e_HIP_SYMBOL); break;
        case 2:  funcSet = &ReinterpretFunctions0;  argIdx = 0; actionType = 1; castStr = getCastType(e_reinterpret_cast); break;
        case 3:  funcSet = &ReinterpretFunctions1;  argIdx = 1; actionType = 1; castStr = getCastType(e_reinterpret_cast); break;
        case 4:  funcSet = &DeviceSymbolFunctions2; argIdx = 2; actionType = 0; castStr = getCastType(e_HIP_SYMBOL); break;
        case 5:  funcSet = &RemoveArgFunctions3;    argIdx = 3; actionType = 2; break; // No cast needed
        case 6:  funcSet = &DeviceSymbolFunctions3; argIdx = 3; actionType = 0; castStr = getCastType(e_HIP_SYMBOL); break;
        case 7:  funcSet = &DeviceSymbolFunctions4; argIdx = 4; actionType = 0; castStr = getCastType(e_HIP_SYMBOL); break;
        case 8:  funcSet = &DeviceSymbolFunctions5; argIdx = 5; actionType = 0; castStr = getCastType(e_HIP_SYMBOL); break;
      }
      if (funcSet->empty()) continue;
      out << tab + foreach_func  << endl;
      unsigned int count = 0;
      string sHIPName;
      for (auto &f : *funcSet) {
        const auto found = CUDA_RUNTIME_FUNCTION_MAP.find(f);
        if (found != CUDA_RUNTIME_FUNCTION_MAP.end()) sHIPName = found->second.hipName.str();
        else {
          const auto found2 = CUDA_DRIVER_FUNCTION_MAP.find(f);
          if (found2 != CUDA_DRIVER_FUNCTION_MAP.end()) sHIPName = found2->second.hipName.str();
        }
        out << (count ? ",\n" : "") << tab_2 << "\"" << sHIPName << "\"";
        count++;
      }
      out << endl_tab << ")" << endl_tab << "{" << endl;
      out << tab_2 << "s{\\b($func)\\s*(\\((?:[^()]+|(?2))*\\))}{ $process_args->($1, $2, " 
          << argIdx << ", " << actionType << ", \"" << castStr << "\") }ges;" << endl;
      out << tab << "}" << endl;
    }
    out << "}" << endl_2;
  }

  void generateDeprecatedAndUnsupportedFunctions(ostream &out) {
    bool bTranslateToRoc = TranslateToRoc;
    bool bTranslateToMIOpen = TranslateToMIOpen;
    TranslateToRoc = false;
    out << "my %hash_" << sHipOnlyUnsupportedFunctions << " = (" << endl;
    for (auto ma = CUDA_RENAMES_MAP().begin(); ma != CUDA_RENAMES_MAP().end(); ++ma) {
      if (Statistics::isUnsupported(ma->second) && ma->second.type != CONV_DEVICE_FUNC && ma->second.type != CONV_DEVICE_TYPE && ma->second.apiType != API_DNN) {
        out << tab << "'" << ma->first.str() << "' => 1," << endl;
      }
    }
    out << ");" << endl_2;
    TranslateToRoc = true;
    out << "my %hash_" << sRocOnlyUnsupportedFunctions << " = (" << endl;
    for (auto ma = CUDA_RENAMES_MAP().begin(); ma != CUDA_RENAMES_MAP().end(); ++ma) {
      if (Statistics::isUnsupported(ma->second) && (ma->second.apiType == API_BLAS || ma->second.apiType == API_SPARSE || ma->second.apiType == API_RAND || ma->second.apiType == API_TENSOR)) {
        out << tab << "'" << ma->first.str() << "' => 1," << endl;
      }
    }
    out << ");" << endl_2;
    TranslateToRoc = false;
    TranslateToMIOpen = true;
    out << "my %hash_" << sMIOpenOnlyUnsupportedFunctions << " = (" << endl;
    for (auto ma = CUDA_RENAMES_MAP().begin(); ma != CUDA_RENAMES_MAP().end(); ++ma) {
      if (Statistics::isUnsupported(ma->second) && ma->second.apiType == API_DNN) {
        out << tab << "'" << ma->first.str() << "' => 1," << endl;
      }
    }
    out << ");" << endl_2;
    TranslateToMIOpen = false;
    out << "my %hash_" << sHipDNNOnlyUnsupportedFunctions << " = (" << endl;
    for (auto ma = CUDA_RENAMES_MAP().begin(); ma != CUDA_RENAMES_MAP().end(); ++ma) {
      if (Statistics::isUnsupported(ma->second) && ma->second.apiType == API_DNN) {
        out << tab << "'" << ma->first.str() << "' => 1," << endl;
      }
    }
    out << ");" << endl_2;
    TranslateToRoc = bTranslateToRoc;
    TranslateToMIOpen = bTranslateToMIOpen;
  }

  void generateDeviceFunctions(ostream &out) {
    out << "my %hash_" << sSupportedDeviceFunctions << " = (" << endl;
    for (auto ma = CUDA_DEVICE_FUNCTION_MAP.begin(); ma != CUDA_DEVICE_FUNCTION_MAP.end(); ++ma) {
      if (!Statistics::isUnsupported(ma->second)) out << tab << "'" << ma->first.str() << "' => 1," << endl;
    }
    out << ");" << endl_2;
    out << "my %hash_" << sUnsupportedDeviceFunctions << " = (" << endl;
    for (auto ma = CUDA_DEVICE_FUNCTION_MAP.begin(); ma != CUDA_DEVICE_FUNCTION_MAP.end(); ++ma) {
      if (Statistics::isUnsupported(ma->second)) out << tab << "'" << ma->first.str() << "' => 1," << endl;
    }
    out << ");" << endl_2;
    out << "my %hash_" << sSupportedDeviceDataTypes << " = (" << endl;
    for (auto ma = CUDA_DEVICE_TYPE_NAME_MAP.begin(); ma != CUDA_DEVICE_TYPE_NAME_MAP.end(); ++ma) {
      if (!Statistics::isUnsupported(ma->second)) out << tab << "'" << ma->first.str() << "' => 1," << endl;
    }
    out << ");" << endl_2;
    out << "my %hash_" << sUnsupportedDeviceDataTypes << " = (" << endl;
    for (auto ma = CUDA_DEVICE_TYPE_NAME_MAP.begin(); ma != CUDA_DEVICE_TYPE_NAME_MAP.end(); ++ma) {
      if (Statistics::isUnsupported(ma->second)) out << tab << "'" << ma->first.str() << "' => 1," << endl;
    }
    out << ");" << endl_2;
}

  bool generate(bool Generate) {
    if (!Generate) return true;
    string dstHipifyPerl = hipify_perl, dstHipifyPerlDir = OutputHipifyPerlDir;
    error_code EC;
    if (!dstHipifyPerlDir.empty()) {
      string sOutputHipifyPerlDirAbsPath = getAbsoluteDirectoryPath(OutputHipifyPerlDir, EC, "output " + hipify_perl);
      if (EC) return false;
      dstHipifyPerl = sOutputHipifyPerlDirAbsPath + "/" + dstHipifyPerl;
    }
    SmallString<128> tmpFile;
    EC = sys::fs::createTemporaryFile(dstHipifyPerl, hipify_perl, tmpFile);
    if (EC) {
      llvm::errs() << "\n" << sHipify << sError << EC.message() << ": " << tmpFile << "\n";
      return false;
    }
    ofstream out(tmpFile.c_str(), ios_base::trunc);
    generateHeader(out);
    string sConv = my + "$apiCalls   = ";
    unsigned int exclude[3] = { CONV_DEVICE_FUNC, CONV_EXTERN_SHARED, CONV_KERNEL_LAUNCH };
    out << "@statNames = (";
    for (unsigned int i = 0; i < NUM_CONV_TYPES - 1; ++i) {
      out << "\"" << counterNames[i] << "\", ";
      if (any_of(exclude, exclude + 3, [&i](unsigned int x) { return x == i; })) continue;
      sConv += "$ft{'" + string(counterNames[i]) + "'}" + (i < NUM_CONV_TYPES - 2 ? " + " : ";");
    }
    if (sConv.back() == ' ') sConv = sConv.substr(0, sConv.size() - 3) + ";";
    out << "\"" << counterNames[NUM_CONV_TYPES - 1] << "\");" << endl;
    generateStatFunctions(out);
    generateSubstFunction(out);
    generateExperimentalSubstitutions(out);
    generateRocSubstitutions(out);
    generateRocSubstitutions(out, true);
    generateSimpleSubstitutions(out);
    generateKernelLaunch(out);
    generateCubNamespace(out);
    generateHostFunctions(out);
    generateDeviceFunctions(out);
    generateDeprecatedAndUnsupportedFunctions(out);
    out << endl << "# Count of transforms in all files" << endl;
    out << my << "%tt;" << endl;
    out << "clearStats(\\%tt, \\@statNames);" << endl;
    out << "$Twarnings = 0;" << endl;
    out << "$TlineCount = 0;" << endl;
    out << my << "$fileCount = @ARGV;" << endl;
    out << "if ($help) {" << endl;
    out << tab << "print STDERR \"$USAGE\\n\";" << endl;
    out << "}" << endl;
    out << "if ($version) {" << endl;
    out << tab << "print STDERR \"HIP version " + sHIP_version + "\\n\";" << endl;
    out << "}" << endl;

    // Build Dictionary and Regex Once Globally
    out << sSimpleMappings << "(); " << endl;
    out << "if ($experimental) {" << endl;
    out << tab << sExperimentalMappings << "();" << endl;
    out << "}" << endl;
    out << "if ($roc) {" << endl;
    out << tab << sRocMappings << "();" << endl;
    out << tab << sMIOpenMappings << "(); " << endl;
    out << "}" << endl;
    out << "if ($miopen) {" << endl;
    out << tab << sMIOpenMappings << "(); " << endl;
    out << "}" << endl;

    // Use a generic C-identifier matcher to bypass Regex Compilation time
    out << "my $master_regex = qr/\\b([a-zA-Z_]\\w*)\\b/;" << endl;

    out << while_ << "(@ARGV) {" << endl;
    out << tab << "$fileName=shift (@ARGV);" << endl;
    out << tab << "my $direxclude = 0;" << endl;
    out << tab << "my $fileDir = dirname(Cwd::realpath($fileName));" << endl;
    out << tab << "while ($fileDir ne dirname($fileDir)) {" << endl;
    out << tab_2 << "if ($exclude_dirhash{$fileDir}) {" << endl;
    out << tab_3 << print << "\"Skipping the file: $fileName in the excluded directory: $fileDir \\n\";" << endl;
    out << tab_3 << "$direxclude = 1;" << endl;
    out << tab_3 << "last;" << endl;
    out << tab_2 << "}" << endl;
    out << tab_2 << "$fileDir = dirname($fileDir);" << endl;
    out << tab << "}" << endl;
    out << tab << "if ($exclude_filehash{$fileName}) {" << endl;
    out << tab_2 <<  print << "\"Skipping the excluded file: $fileName \\n\";" << endl_tab << "}" << endl;
    out << tab << unless_ << "($direxclude or $exclude_filehash{$fileName}) {" << endl;
    out << tab_2 << "if ($inplace) {" << endl;
    out << tab_3 << my << "$file_prehip = \"$fileName\" . \".prehip\";" << endl;
    out << tab_3 << my << "$infile;" << endl;
    out << tab_3 << my << "$outfile;" << endl;
    out << tab_3 << "if (-e $file_prehip) {" << endl;
    out << tab_4 << "$infile  = $file_prehip;" << endl;
    out << tab_4 << "$outfile = $fileName;" << endl;
    out << tab_3 << "} else {" << endl;
    out << tab_4 << "system (\"cp $fileName $file_prehip\");" << endl;
    out << tab_4 << "$infile = $file_prehip;" << endl;
    out << tab_4 << "$outfile = $fileName;" << endl_tab_3 << "}" << endl;
    out << tab_3 << "open(INFILE,\"<\", $infile) or die \"error: could not open $infile\";" << endl;
    out << tab_3 << "open(OUTFILE,\">\", $outfile) or die \"error: could not open $outfile\";" << endl;
    out << tab_3 << "$OUTFILE = OUTFILE;" << endl;
    out << tab_2 << "} else {" << endl;
    out << tab_3 << "open(INFILE,\"<\", $fileName) or die \"error: could not open $fileName\";" << endl;
    out << tab_3 << "if ($hipFileName ne \"\") {" << endl;
    out << tab_4 << "open(OUTFILE,\">\", $hipFileName) or die \"error: could not open $hipFileName\";" << endl;
    out << tab_4 << "$OUTFILE = OUTFILE;" << endl;
    out << tab_3 << "} else {" << endl;
    out << tab_4 << "$OUTFILE = STDOUT;" << endl_tab_3 << "}" << endl_tab_2 << "}" << endl;
    out << tab_2 << "# Count of transforms in this file" << endl;
    out << tab_2 << "clearStats(\\%ft, \\@statNames);" << endl;
    out << tab_2 << my << "$countKeywords = 0;" << endl;
    out << tab_2 << my << "$warnings = 0;" << endl;
    out << tab_2 << my << "$lineCount = 0;" << endl;
    out << tab_2 << "%convertedTags = ();" << endl;
    out << tab_2 << "%tagsToConvertedTags = ();" << endl;
    out << tab_2 << "undef $/;" << endl;
    out << tab_2 << "# Read whole file at once, so we can match newlines" << endl;
    out << tab_2 << while_ << "(<INFILE>) {" << endl;
    out << tab_3 << "$countKeywords += m/__global__/;" << endl;
    out << tab_3 << "$countKeywords += m/__shared__/;" << endl;
    out << tab_3 << unless_ << "($quiet_warnings) {" << endl;
    out << tab_4 << my << "@lines = split /\\n/, $_;" << endl;
    out << tab_4 << my << "$line_num = 0;" << endl;
    out << tab_4 << foreach << "(@lines) {" << endl;
    out << tab_5 << "$line_num++;" << endl;

    out << tab_5 << "my %unique_words = map { $_ => 1 } m/\\b([a-zA-Z_]\\w*)\\b/g;" << endl;
    out << tab_5 << "foreach my $func (keys %unique_words) {" << endl;
    out << tab_6 << "if (!$experimental && exists $experimental_funcs{$func}) {" << endl;
    out << tab_7 << "print STDERR \"  " << warning << "experimental ROCm HIP identifier: $func $experimental_funcs{$func}\\n\";" << endl;
    out << tab_7 << "$warnings++;" << endl;
    out << tab_6 << "}" << endl;
    out << tab_6 << "if (exists $removed_funcs{$func}) {" << endl;
    out << tab_7 << "my $cuda = (index(lc($func), \"cudnn\") == 0) ? \"CUDNN\" : \"CUDA\";" << endl;
    out << tab_7 << "print STDERR \"  " << warning << "removed CUDA identifier: $func since $cuda $removed_funcs{$func}\\n\";" << endl;
    out << tab_7 << "$warnings++;" << endl;
    out << tab_6 << "}" << endl;
    out << tab_6 << "if (exists $deprecated_funcs{$func}) {" << endl;
    out << tab_7 << "my $cuda = (index(lc($func), \"cudnn\") == 0) ? \"CUDNN\" : \"CUDA\";" << endl;
    out << tab_7 << "print STDERR \"  " << warning << "deprecated CUDA identifier: $func since $cuda $deprecated_funcs{$func}\\n\";" << endl;
    out << tab_7 << "$warnings++;" << endl;
    out << tab_6 << "}" << endl;

    out << tab_6 << "if ($roc) {" << endl;
    out << tab_7 << "if (exists $hash_RocOnlyUnsupportedFunctions{$func}) {" << endl;
    out << tab_8 << "print STDERR \"  " << warning << "unsupported ROC identifier: $func\\n\";" << endl;
    out << tab_8 << "$warnings++;" << endl;
    out << tab_7 << "}" << endl;
    out << tab_7 << "if (exists $hash_MIOpenOnlyUnsupportedFunctions{$func}) {" << endl;
    out << tab_8 << "print STDERR \"  " << warning << "unsupported MIOpen identifier: $func\\n\";" << endl;
    out << tab_8 << "$warnings++;" << endl;
    out << tab_7 << "}" << endl;
    out << tab_6 << "} else {" << endl;
    out << tab_7 << "if (exists $hash_HipOnlyUnsupportedFunctions{$func}) {" << endl;
    out << tab_8 << "print STDERR \"  " << warning << "unsupported HIP identifier: $func\\n\";" << endl;
    out << tab_8 << "$warnings++;" << endl;
    out << tab_7 << "}" << endl;
    out << tab_7 << "if ($miopen) {" << endl;
    out << tab_8 << "if (exists $hash_MIOpenOnlyUnsupportedFunctions{$func}) {" << endl;
    out << tab_9 << "print STDERR \"  " << warning << "unsupported MIOpen identifier: $func\\n\";" << endl;
    out << tab_9 << "$warnings++;" << endl;
    out << tab_8 << "}" << endl;
    out << tab_7 << "} else {" << endl;
    out << tab_8 << "if (exists $hash_HipDNNOnlyUnsupportedFunctions{$func}) {" << endl;
    out << tab_9 << "print STDERR \"  " << warning << "unsupported hipDNN identifier: $func\\n\";" << endl;
    out << tab_9 << "$warnings++;" << endl;
    out << tab_8 << "}" << endl;
    out << tab_7 << "}" << endl;
    out << tab_6 << "}" << endl;

    out << tab_6 << "if (exists $hash_UnsupportedDeviceDataTypes{$func}) {" << endl;
    out << tab_7 << "print STDERR \"  " << warning << "unsupported device data type identifier: $func\\n\";" << endl;
    out << tab_7 << "$warnings++;" << endl;
    out << tab_6 << "}" << endl;

    out << tab_6 << "if (exists $hash_UnsupportedDeviceFunctions{$func}) {" << endl;
    out << tab_7 << "if ($_ =~ m/\\b$func\\b\\s*\\(/ && $_ !~ m/\\w+::$func\\b\\s*\\(/) {" << endl;
    out << tab_8 << "print STDERR \"  " << warning << "unsupported device function \\\"$func\\\": $_\\n\";" << endl;
    out << tab_8 << "$warnings++;" << endl;
    out << tab_7 << "}" << endl;
    out << tab_6 << "}" << endl;
    out << tab_5 << "}" << endl;
    out << tab_4 << "}" << endl;
    out << tab_3 << "}" << endl;

    out << tab_3 << "if ($roc) {" << endl;
    out << tab_4 << sRocIncludes << "(); " << endl;
    out << tab_4 << sMIOpenIncludes << "();" << endl;
    out << tab_3 << "}" << endl;
    out << tab_3 << "if ($miopen) {" << endl;
    out << tab_4 << sMIOpenIncludes << "();" << endl;
    out << tab_3 << "}" << endl;
    out << tab_3 << "if ($experimental) {" << endl;
    out << tab_4 << "experimentalIncludes();" << endl;
    out << tab_3 << "}" << endl;
    out << tab_3 << "simpleIncludes();" << endl;

    // Execute the globally compiled master regex
    out << tab_3 << "if (defined $master_regex) {" << endl;
    out << tab_4 << "$_ =~ s/$master_regex/do {" << endl;
    out << tab_5 << "my $match = $1;" << endl;
    out << tab_5 << "if (exists $mappings{$match}) {" << endl;
    out << tab_6 << "my $b = $mappings{$match}->{rep};" << endl;
    out << tab_6 << "my $t = $mappings{$match}->{type};" << endl;
    out << tab_6 << "$ft{$t}++;" << endl;
    out << tab_6 << "$convertedTags{$b}++;" << endl;
    out << tab_6 << "$convertedTagsTotal{$b}++;" << endl;
    out << tab_6 << "$tagsToConvertedTags{$match} = $b;" << endl;
    out << tab_6 << "$tagsToConvertedTagsTotal{$match} = $b;" << endl;
    out << tab_6 << "$b;" << endl; // Return the replacement
    out << tab_5 << "} else {" << endl;
    out << tab_6 << "$match;" << endl; // Return the original word untouched
    out << tab_5 << "}" << endl;
    out << tab_4 << "}/ge;" << endl;
    out << tab_3 << "}" << endl;

    out << tab_3 << "if (!$cuda_kernel_execution_syntax || $hip_kernel_execution_syntax) {" << endl;
    out << tab_4 << sTransformKernelLaunch << "();" << endl;
    out << tab_3 << "}" << endl;
    out << tab_3 << sTransformCubNamespace << "();" << endl;
    out << tab_3 << my << "$hasDeviceCode = $countKeywords + $ft{'" << counterNames[CONV_DEVICE_FUNC] << "'} + $ft{'" << counterNames[CONV_DEVICE_TYPE] << "'};" << endl;

    out << tab_3 << "foreach my $func (keys %hash_SupportedDeviceDataTypes) {" << endl;
    out << tab_4 << "my $c = () = $_ =~ m/\\b$func\\b/g;" << endl;
    out << tab_4 << "if ($c) { $ft{'" << counterNames[CONV_DEVICE_TYPE] << "'} += $c; }" << endl;
    out << tab_3 << "}" << endl;

    out << tab_3 << "foreach my $func (keys %hash_SupportedDeviceFunctions) {" << endl;
    out << tab_4 << "my $c = () = $_ =~ m/\\b$func\\b\\s*\\((?!\\s*void)/g;" << endl;
    out << tab_4 << "if ($c) { $ft{'" << counterNames[CONV_DEVICE_FUNC] << "'} += $c; }" << endl;
    out << tab_3 << "}" << endl;

    out << tab_3 << unless_ << "($quiet_warnings) {" << endl;

    out << tab_4 << "# Copy into array of lines, process line-by-line to show warnings" << endl;
    out << tab_4 << "if ($hasDeviceCode or (/\\bcu|CU/) or (/<<<.*>>>/)) {" << endl;
    out << tab_5 << my << "@lines = split /\\n/, $_;" << endl;
    out << tab_5 << my << "$line_num = 0;" << endl;
    out << tab_5 << foreach << "(@lines) {" << endl;
    out << tab_6 << "$line_num++;" << endl;
    out << tab_6 << "# Remove any whitelisted words" << endl;
    out << tab_6 << foreach << "$w (@whitelist) {" << endl;
    out << tab_7 << "redo if s/\\b$w\\b/ZAP/" << endl_tab_6 << "}" << endl;
    out << tab_6 << "if ((/(\\bcuda[A-Z]\\w+)/) or ((/<<<.*>>>/) and ($hip_kernel_execution_syntax))) {" << endl;
    out << tab_7 << "# Flag any remaining code that look like cuda API calls: may want to add these to hipify" << endl;
    out << tab_7 << "$warnings++;" << endl;
    out << tab_7 << print << "\"  warning: $fileName:#$line_num : $_\\n\";" << endl_tab_6 << "}" << endl_tab_5 << "}" << endl;
    out << tab_4 << "}" << endl_tab_3 << "}" << endl;
    out << tab_3 << "transformHostFunctions();" << endl_2;
    out << tab_3 << "# TODO: would like to move this code outside loop but it uses $_ which contains the whole file" << endl;
    out << tab_3 << unless_ << "($no_output) {" << endl;
    out << tab_4 << sConv << endl;
    out << tab_4 << my << "$kernStuff  = $hasDeviceCode + $ft{'" << counterNames[CONV_KERNEL_LAUNCH] << "'} + $ft{'" << counterNames[CONV_DEVICE_FUNC] << "'} + $ft{'" << counterNames[CONV_DEVICE_TYPE] << "'};" << endl;
    out << tab_4 << my << "$totalCalls = $apiCalls + $kernStuff;" << endl;
    out << tab_4 << "$is_dos = m/\\r\\n$/;" << endl;
    out << tab_4 << "if ($totalCalls and ($kernStuff != 0)) {" << endl;
    out << tab_5 << "# TODO: implement hipify-clang's logic with header files AMAP" << endl;
    out << tab_5 << "print $OUTFILE '#include \"hip/hip_runtime.h\"' . ($is_dos ? \"\\r\\n\" : \"\\n\");" << endl_tab_4 << "}" << endl;
    out << tab_4 << "print $OUTFILE  \"$_\";" << endl_tab_3 << "}" << endl;
    out << tab_3 << "$lineCount = $_ =~ tr/\\n//;" << endl_tab_2 << "}" << endl;
    out << tab_2 << my << "$totalConverted = totalStats(\\%ft);" << endl;
    out << tab_2 << "if (($totalConverted+$warnings) and $print_stats) {" << endl;
    out << tab_3 << "printStats(\\%ft, $warnings, $lineCount, $fileName, 0);" << endl_tab_2 << "}" << endl;
    out << tab_2 << "# Update totals for all files" << endl;
    out << tab_2 << "addStats(\\%tt, \\%ft);" << endl;
    out << tab_2 << "$Twarnings += $warnings;" << endl;
    out << tab_2 << "$TlineCount += $lineCount;" << endl;
    out << endl_tab << "}   # Unless filtered directory or file" << endl;
    out << "}" << endl;
    out << "# Print total stats for all files processed" << endl;
    out << "if ($print_stats and ($fileCount > 1)) {" << endl;
    out << tab << "printStats(\\%tt, $Twarnings, $TlineCount, \"GLOBAL\", 1);" << endl;
    out << tab << print << "\"\\n\";" << endl;
    out << "}" << endl;
    out.flush();
    bool ret = true;
    EC = sys::fs::copy_file(tmpFile, dstHipifyPerl);
    if (EC) {
      llvm::errs() << "\n" << sHipify << sError << EC.message() << ": while copying " << tmpFile << " to " << dstHipifyPerl << "\n";
      ret = false;
    }
    if (!SaveTemps) sys::fs::remove(tmpFile);
    return ret;
  }
}
